name: Blog

on:
  push:
    branches: [ bloggy ]


jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v1
    - uses: r-lib/actions/setup-pandoc@v1
    - name: Install rmarkdown
      run: Rscript -e 'install.packages("rmarkdown")'
